--
-- PostgreSQL database dump
--

-- Dumped from database version 15.10
-- Dumped by pg_dump version 15.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    category_name character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    product_name character varying(255),
    unit_price double precision,
    units_in_stock integer,
    category_id integer,
    image_url character varying(2048)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, category_name) FROM stdin;
2	Vitamins and Supplements
3	Skincare
4	Antibiotics
5	Cold and Flu
6	Baby Care
1	Painkiller
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, product_name, unit_price, units_in_stock, category_id, image_url) FROM stdin;
1	Apranax	70	100	1	https://cdn.hekimce.com/uploads/2022/basliksiz-1-1671739805.jpg
4	Parol	65	35	1	https://ilacfiyati.com/dosyalar/2019/05/PAROL-500-MG-30-TABLET.png
5	Baby Lotion	100	20	6	https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/him/him50116/l/13.jpg
6	Diapers	130	15	6	https://m.media-amazon.com/images/I/71ngYLU5SgL._AC_UF1000,1000_QL80_.jpg
8	Balen Vitamin C	300	15	2	https://cdn.dsmcdn.com/mnresize/600/-/ty288/product/media/images/20220108/16/23384858/353863642/1/1_org_zoom.jpg
9	Venatura Iron Supplement	269	15	2	https://cdn.dsmcdn.com/mnresize/400/-/ty1605/prod/QC/20241127/15/068e5ade-d1f2-35d2-9f4d-03e4e8988342/1_org_zoom.jpg
29	Baby Powder	150	12	6	https://cdn.dsmcdn.com/mnresize/600/-/ty1525/product/media/images/prod/QC/20240905/20/ca389a94-5abd-3be4-81bb-b8ee5ac80ffa/1_org_zoom.jpg
10	Arveles	75	10	1	https://icdn.ensonhaber.com/crop/1200x0/resimler/diger/kok/2023/11/27/6564a49f5d752191__w1200xh800.jpg
11	Venatura Vitamin A	150	15	2	https://cdn.akakce.com/z/venatura/venatura-vitamin-a-palmitat-60-yumusak-kapsul.jpg
12	Venatura B12 Vitamin	200	10	2	https://www.dermoeczanem.com/venatura-vitamin-b12-odt-takviye-edici-gida-90-tablet-venatura-156980-69-B.jpg
13	Venatura Vitamin E	250	13	2	https://cdn.cimri.io/image/1200x1200/https://cdn.cimri.io/image/200x200/solgar-vitamin-e-200-iu-50-kapsul_268653196.jpg
14	Redoxon Kids Vitamin	250	10	2	https://productimages.hepsiburada.net/s/50/375-375/11033765347378.jpg
15	Venatura Vitamin D	250	7	2	https://cdn.akakce.com/z/venatura/venatura-vitamin-d3-ve-menaquinon-7-20-ml.jpg
16	Sebamed Deep Cleaning Foam	180	10	3	https://assets.sebamedusa.com/spree/images/1212/large/1152781.jpg?1621079734
17	Sebamed Deep Cleaning Facial Toner	180	10	3	https://assets.sebamedusa.com/spree/images/1185/large/6610781.jpg?1621079602
18	Sebamed Deep Moisturizing Care Jel	180	10	3	https://sch.sachane.com/images/thumbnails/383/383/detailed/59/sebamed-sivilceye-yatkin-ciltler-icin-bakim-jeli-50ml.jpg
19	Face Mask	150	15	3	https://m.media-amazon.com/images/I/81XRShv2tmL.jpg
30	Baby Oil	150	12	6	https://m.media-amazon.com/images/I/61CqiYK39fL.jpg
32	WHEY Protein	3000	15	2	https://contents.mediadecathlon.com/p2573280/k$a6d2c9489303277ce6f653cf03759c22/sq/8337049.jpg?format=auto&f=800x0
20	Eqiceft Antibiotics	100	10	4	https://www.tumekip.com.tr/yuklenen/urunler/1465282417/b-eqiceft-1-g-im-flakon-14652890422532.jpg
33	Dolorex	75	20	1	https://sehirgazetesicomtr.teimg.com/sehirgazetesi-com-tr/uploads/2023/10/dolorex-nedir-ne-icin-kullanilir-detay2.png
22	Amoklavin Antibiotics	100	10	4	https://www.deva.com.tr/uploads/product_images/big/LLCu6unQGneoFj0LArt8.jpg
21	Cipro Antibiotics	100	10	4	https://dkud4u09qff41.cloudfront.net/Products/811d094b-7e21-4b62-9f80-981b0aa1c1f2.jpeg
24	Aferin	120	10	5	https://imgscdn.stargazete.com/imgsdisk/2020/09/18/aferin-ilaci-ne-ise-yarar-799_2.jpg
25	Nurofen	120	10	5	https://img.superhaber.com/storage/files/images/2020/03/04/nurofen-cold-flu-24s-1-20595-lwZ6_cover.jpg
26	Theraflu	120	10	5	https://i-cf65.ch-static.com/content/dam/cf-consumer-healthcare/health-professionals/tr_TR/respiratory-health/packshots/750x421_therafluforte.png?auto=format
27	Coldaway	120	10	5	https://ilacfiyati.com/dosyalar/2020/04/COLDAWAY-C-200-MG-30-MG-300-MG-FILM-TABLET.png
28	Baby Shampoo	150	12	6	https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/him/him50123/l/13.jpg
23	lip moisturizer	100	10	3	https://images-us.nivea.com/-/media/miscellaneous/media-center-items/9/6/f/48f6dcfb968a4ff980ea1194994d581b-web_1010x1180_transparent_png.png
31	Baby Colonger	150	12	6	https://www.sunonline.lk/cdn/shop/files/NS-PBTS-100-01_800x.jpg?v=1733130099
3	Colonge	60	30	1	https://barbershop-bg.com/wp-content/uploads/2022/12/eau-de-cologne-olive-glass.jpg
7	Baby Wipes	110	20	6	https://static.ticimax.cloud/5011/uploads/urunresimleri/buyuk/luckido-baby-wipes-bebek-islak-mendili-9-b803.jpg
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 6, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 34, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- PostgreSQL database dump complete
--

